http://localhost/oauth/authorize?redirect_uri=http%3A%2F%2Flocalhost%0A&response_type=code&client_id=3
http://stsk.herokuapp.com/oauth/authorize?redirect_uri=http%3A%2F%2Flocalhost%0A&response_type=code&client_id=3

# @host = heroku

### Get Token
POST /oauth/token HTTP/1.1
Host: {{ host }}
Content-Type: application/x-www-form-urlencoded

# grant_type=client_credentials
grant_type=authorization_code
&client_id=
&client_secret=
&code=
&redirect_uri=

### user
GET /api/user HTTP/1.1
Host: {{ host }}
Accept: application/json
Authorization: Bearer {{ token }}

### tasks
GET /api/tasks HTTP/1.1
Host: {{ host }}
Accept: application/json
Authorization: Bearer {{ token }}

### events
GET /api/events HTTP/1.1
Host: {{ host }}
Accept: application/json
Authorization: Bearer {{ token }}

